name = "viewroyal-intelligence"
compatibility_date = "2026-02-10"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"

routes = [
  { pattern = "viewroyal.ai/*", zone_name = "viewroyal.ai" }
]

[triggers]
crons = ["*/5 * * * *"]

[vars]
VIMEO_PROXY_URL = "https://vimeo-proxy.kpeatt.workers.dev"
VIMEO_PROXY_FALLBACK_URL = "https://vimeo-proxy.onrender.com"

[observability]
enabled = true
[observability.logs]
enabled = true
invocation_logs = true
